### ISSUE TITLE
Test Swiss + Nintendont

### ISSUE THREAD

**Issue by danmons** [retronas/retronas#311]
A note to test Swiss running on Nintendont with BBA emulation, to see if Swiss can see the virtual BBA and use it for FSP game loading.

**Comment by drinksomewhiskey** [comment]
Hey Dan, did you have any luck with this? If so, would you provide general steps to set it up on a WII/U? I'm wondering if it's the same as Swiss on GC.

**Comment by sairuk** [comment]
nintendont doesn't support homebrew, while you can attempt to boot the isos from the swiss release it boots to a blackscreen like a lot of other homebrew folks have tested.

feel free to reopen this to play with it again but for now i've tried it and it wont boot the iso
