### ISSUE TITLE
ps3netsrv make the ROMS path configurable (and probably make it general)

### ISSUE THREAD

**Issue by AdrianJesusSilva** [retronas/retronas#392]
ps3netsrv make the ROMS path configurable (and probably make it general)

Hello to everyone

I open this issue to ask to make the rom paths for the ps3netsrv configurable, the reasoning for this is that I installed retronas in a VM inside of TrueNAS Scale and configure a bridge NIC so the VM can talk to the host via a SMB Share (probably NFS Share is better but couldn't make it work).

Looking in the retronas config program, did not find anywhere to changes the paths of the roms for the ps3netsrv, but, looking how the final result of the config I did see that the folders are symbolic links to the roms folder of the retronas, like this example
 
![imagen](https://github.com/retronas/retronas/assets/26579895/4ec92ece-70bb-41b0-b855-7b6017940b47)

What I did to make it work as I need it is to delete the old PS3ISO symbolic link and create a new one pointing the isos folders inside the SMB Share (which is a dataset) that contains my PS3 backups of my games like this

![imagen](https://github.com/retronas/retronas/assets/26579895/7c2acc79-450d-400c-b323-29a25db0a0f4)

So again what I am asking is to make this process configurable so we can point to another isos or games folder.

Hope this find you well and have a good day

**Comment by sairuk** [comment]
Thank you for the suggestion, we prefer feature requests through Discussions, however i shall answer here.

To keep things simple for the end user and the project we maintain a standard base deploy, your use case is well outside the standard and would add additional complexity we'd need to manage so we wont be adding this customisation functionality at this time.

That said we recently added the ability for more advanced users to write and run their own "modules" (ansible playbook) from the Tools menu exactly for these corner cases.

Please have a look here https://github.com/retronas/retronas/wiki/Local-Module

**Comment by AdrianJesusSilva** [comment]
Thanks in advance for the answer, sorry for not doing the corret way by opening a issue, will check the wiki about the local module
