### ISSUE TITLE
Xlink kai install script issue

### ISSUE THREAD

**Issue by Beerman-pixel** [retronas/retronas#393]
In line 102 of the xlink kai install script (/ansible/install_xlink-kai.yml) it says "ansible.mport.playbook" instead of "ansible.import.playbook" which causes an error when running the script

**Comment by sairuk** [comment]
Thanks, this typo is now fixed in the testing branch

Thankfully this should not have prevented the install of the application as ln:102 is just logging the package id for our internal use

**Comment by Beerman-pixel** [comment]
Well the typo gave me this output when installing the application, thats why i filed the issue

![grafik](https://github.com/retronas/retronas/assets/75475315/3393aea3-e32d-4099-b5dd-fe5429655479)
