### ISSUE TITLE
How to add new SAMBA shares?

### ISSUE THREAD

**Issue by toaks2804** [retronas/retronas#397]
I am using the retronas with MiSTer currently. Under the RetroSMB folder I have a retronas share, a pi share, and a Mister share. I want to add 2 shares, one for picture backups and one for backing up random files to access from my Mac and windows pcs. I cannot figure out how to create them. Any help?

**Comment by sairuk** [comment]
There is some information on configuring custom shares here https://github.com/orgs/retronas/discussions/116

How to configure custom Samba shares is outside the scope of RetroNAS refer to the officia doco from the samba project here https://www.samba.org/samba/docs/

Also please use Discussions for this kind of inquiry, issues are for problems with the platform.
https://github.com/orgs/retronas/discussions
