### ISSUE TITLE
3DS QR Code Generator - issues when RetroNAS has multiple network interfaces

### ISSUE THREAD

**Issue by citizen-why** [retronas/retronas#400]
Issue: I have a retronas with two network interfaces active. When generating the 3DS QR codes, the url included in the html pages and embedded in the QR codes are corrupt, in that they attempt to use the IPs of both active interfaces. the form of the url is thus

http://[IP_INTERFACE_1] [[IP_INTERFACE_1]/3ds/cia//[FILENAME].cia

**Comment by sairuk** [comment]
thanks this is a known issue; to properly fix this there is some work to do to allow the user to select the appropriate int to generate the code for and storing and recalling the settings at runtime

**Comment by sairuk** [comment]
https://github.com/retronas/retronas/commit/497ac89326d9df3f45b34938e7f8dfba4671c51d adds the requirement to generate the ip address from a user selected interface, this should address this issue
