### ISSUE TITLE
FR: Add folder structure/symlinks for emulatorJS

### ISSUE THREAD

**Issue by charles-spurgeon** [retronas/retronas#401]
Would be cool to have an option for a user to add a populated folder structure for the emulatorJS [project](https://emulatorjs.org).

**Comment by sairuk** [comment]
Discussions are for requests https://github.com/orgs/retronas/discussions

Taking a quick look at that project there is no defined folder structure for the project. It is up to the user to dictate it in the webpage they configure so you could use any current structure when configuring the emulator page.

I already run a wrapper/generator here with mame machine wasm builds. We could perhaps (similar to 3ds) write a page generator. I have added this and emularity to the Ideas page.
