### ISSUE TITLE
Passwords do not match, press enter to continue

### ISSUE THREAD

**Issue by COIh0rp** [retronas/retronas#407]
### Details

I'm not able to sign into the retrosmb share even through it is visible on my network. I'm trying to use config to reset the password with hope that will help. However, when i go to change the password in config the termnial just says passwords do not match, press enter. I press enter and nothing happens, so it does not seem possible to change the password.

**Comment by sairuk** [comment]
i've just tested this on both the main and testing branches here and it works as intended.

Config -> Password .... enter your password in the first box, press the down arrow and enter the password again in the second box then select OK and the password will be successfully updated

**Comment by MasterPhooey** [comment]
Same issue on new install on debian and can’t connect to smb no login works

maybe related to
https://github.com/retronas/retronas/issues/406

**Comment by kosinjak** [comment]
Hello! I encountered this issue and it got fixed. The changes were merged into the main branch. Try again and see if it works!!
