### ISSUE TITLE
Gogdownloaders Login process not working

### ISSUE THREAD

**Issue by Mythris29** [retronas/retronas#408]
### Details

![image](https://github.com/user-attachments/assets/1759963e-2c0a-4ae5-9a09-27eb1e248a1b)

This has worked in the past for me but recently I tried to login and update my gog downloads and I ran into this error. 

I attempted to delete the gogdownloader and reinstall it
I also attempted to manually copy the cookie over
Tried updating the debian os and all modules

Each time I get the error above that I'm posting in a screenshot

**Comment by sairuk** [comment]
looks like gog changed their page and broke the underlying tool, nothing we can do from a retronas level until the tool is fixed

**Comment by Mythris29** [comment]
I'll submit it over there and see what comes of it. Thank you!

**Comment by sairuk** [comment]
We are actually using my fork of this at the moment so I will be looking at it at some point. 

I took a look for a bit last night and didn't come to a solution. It _appears_ it is only the login process that is broken so if you obtain your cookies from firefox and save them for the app to use it may work

i will leave this open so people can find it easily until we have a working tool

**Comment by Mythris29** [comment]
I'm not sure if this is helpful or not but this is after importing the cookie from firefox

![image](https://github.com/user-attachments/assets/d2cd9b25-b28f-4d0f-816b-84f08195ee09)


I'm not sure if I needed to edit the gog-cookies.dat file to a certain format

**Comment by sairuk** [comment]
nice thanks, i'll give it a go as well see what i can work out as a workaround for now

**Comment by sairuk** [comment]
gave it a go and it works ok as a workaround, tried sync and downloads

1. Using this addon (not vouching for it, decide for yourself if you are happy to use this, I am using a test account) https://addons.mozilla.org/en-US/firefox/search/?q=Export%20Cookies
2. Login to your gog account using Firefox
3. Export the cookies for `gog.com` to `gog-cookies.dat` using the addon
4. Place gog-cookies.dat in the ~/.gogrepo directory
5. Run a sync, the script will convert it to the correct format on save

```
16:55:32 | loading local manifest...
16:55:32 | fetching game product data (page 1)...
16:55:35 | found 4 games !!
16:55:35 | (1 / 4) fetching game details for beneath_a_steel_sky...
16:55:42 | successfully found md5 9c136a1b34d759bc8fb748eca732f092 for setup_beneath_a_steel_sky_1.0_(20270).exe
16:55:47 | successfully found md5 c9a32209264f0aadc20793cb15b2b2ad for beneath_a_steel_sky_enUS_1_0_33348.pkg
16:55:52 | successfully found md5 5cc68247b61ba31e37e842fd04409d98 for beneath_a_steel_sky_en_gog_2_20150.sh
16:55:58 | successfully found md5 9c136a1b34d759bc8fb748eca732f092 for setup_beneath_a_steel_sky_1.0_(20270).exe
16:56:03 | successfully found md5 66e167fb915fbde75b32df34ddb545ff for beneath_a_steel_sky_deDE_1_0_33348.pkg
16:56:08 | successfully found md5 5cc68247b61ba31e37e842fd04409d98 for beneath_a_steel_sky_en_gog_2_20150.sh
16:56:13 | successfully found md5 9c136a1b34d759bc8fb748eca732f092 for setup_beneath_a_steel_sky_1.0_(20270).exe
16:56:19 | successfully found md5 30320daddcae50f69bce01d5d778d7fd for beneath_a_steel_sky_esES_1_0_33348.pkg
16:56:24 | successfully found md5 5cc68247b61ba31e37e842fd04409d98 for beneath_a_steel_sky_en_gog_2_20150.sh
16:56:30 | successfully found md5 9c136a1b34d759bc8fb748eca732f092 for setup_beneath_a_steel_sky_1.0_(20270).exe
16:56:36 | successfully found md5 04b3813496757fd56ea2df3cc2289453 for beneath_a_steel_sky_frFR_1_0_33348.pkg
16:56:41 | successfully found md5 5cc68247b61ba31e37e842fd04409d98 for beneath_a_steel_sky_en_gog_2_20150.sh
16:56:47 | successfully found md5 9c136a1b34d759bc8fb748eca732f092 for setup_beneath_a_steel_sky_1.0_(20270).exe
16:56:52 | successfully found md5 fcb726d723f3b34dcf24c7f958125672 for beneath_a_steel_sky_itIT_1_0_33348.pkg
16:56:58 | successfully found md5 5cc68247b61ba31e37e842fd04409d98 for beneath_a_steel_sky_en_gog_2_20150.sh
16:57:18 | (2 / 4) fetching game details for dex...
16:57:25 | successfully found md5 e1d4afae8103131dad53558e92c8bb3d for setup_dex_6.0.0.0_(16717).exe
16:57:31 | successfully found md5 d81016c66570c429f1580a1a1fbbef1b for setup_dex_6.0.0.0_(16717)-1.bin
16:57:35 | successfully found md5 1fca46dcf6cb0be129441e3dbaa7141a for patch_dex_5.4.0.0_(10932)_to_6.0.0.0_(16717).exe
16:57:41 | successfully found md5 ce89cc922833e810ec3db90649f5a802 for dex_en_6000_16720.pkg
16:57:47 | successfully found md5 3d6f8797fab72dcb867c92bf5a84b4dd for dex_en_6_0_0_0_build_5553_17130.sh
16:57:54 | successfully found md5 d6f358b5dec54fc7203df5393ded7934 for patch_dex_2.0.1.2.sh
16:58:00 | successfully found md5 eed9116e43583c5cb985ed07fc06414d for patch_dex_2.1.2.3.sh
16:58:06 | successfully found md5 c22d4b28a3747dc4b4d96d8719b7bc7b for patch_dex_2.2.3.4.sh
16:58:35 | (3 / 4) fetching game details for final_liberation_warhammer_epic_40000...
16:58:41 | successfully found md5 7d9dde9a5d505efb06374d8d1adf3416 for setup_wh40k_final_liberation_2.0.0.4.exe
16:58:50 | (4 / 4) fetching game details for warhammer_skulls_2023_free_game_digitial_goodie_pack_goodies...
16:59:12 | saving manifest...
16:59:12 | --
16:59:12 | total time: 0:03:39.129994
16:59:12 | exiting...
```

the exported `gog-cookies.dat` should contain data similar to this before the script runs

```
# Netscape HTTP Cookie File

www.gog.com FALSE / FALSE 1722667917  front_ab  new 
.gog.com  TRUE  / TRUE  1723013521  csrf  true
.gog.com  TRUE  / FALSE 0 cart_token  <value>
login.gog.com FALSE / TRUE  1739688806  galaxy-login-s  <value>
login.gog.com FALSE / TRUE  1753944806  galaxy-login-al <value>
.gog.com  TRUE  / TRUE  1722495217  gog_us  <value>
.gog.com  TRUE  / FALSE 1753944817  gog_lc  <value>
.gog.com  TRUE  / TRUE  1746082417  gog-al  <value>
```

**Comment by Mythris29** [comment]
I imported my cookie via firefox again and it looks like it's very similar to your format. Renamed it to gog-cookies.dat and tried to download the manafest. No luck with the same error I posted above. I also tried deleting the manafest just to see if it was corrupt or something without luck. I also tried reinstalling gogdownloader tool again from retronas just to see if something was corrupted with the tool. No luck. I am able to reach out to the internet from the restronas host so I don't think it's network related.

I also downloaded gogcli on my windows desktop and tried it (using the same cookie from firefox just altered to the format they want) and it worked. Was able to download the manafest and a couple of games from Gog so I think my cookie is working or at least it has the right information inside it for another program to use it. The desktop I tried this on is the same deskto I got the cookie on so that would be a possible variable (if gog is restricting cookies to IP addresses now)


Any ideas of what I could try next to troubleshoot this?

**Comment by sairuk** [comment]
i performed the same operation on 3 different machines and it works for me

only thing i can suggest is make sure you export the cookies for `gog.com` not `www.gog.com` and dont use the `login` option

**Comment by OGDemoss** [comment]
I tried the workaround but still doesn't work for me like Mythris29.

![Screenshot_20240801_061448](https://github.com/user-attachments/assets/6059c197-6db0-4d02-af3b-a32bd327ebe6)

**Comment by sairuk** [comment]
ok i've managed to replicate this now on my production retronas, it would appear behaviour changed between python 3.9.x  and 3.11.x ... my test host has the latter and imported the exported cookies fine, also converted the cookies to the expected format

**Comment by sairuk** [comment]
this hacky thing will convert the firefox exported cookies to compatible cookies with python 3.9, put it in a directory with the exported `cookies-gog-com.txt` and run it then use the saved `gog-cookies.dat`

```
#!/usr/bin/env python3

import datetime

gog_cookies_out = "gog-cookies.dat"
cookies = open(r"cookies-gog-com.txt",'r')

with open(gog_cookies_out,'w') as f:

    f.write("#LWP-Cookies-2.0\n")
    for line in cookies.readlines():
        pieces = line.split()
        if (len(pieces) == 7) and (pieces[0] != "#"):
            d = datetime.datetime.utcfromtimestamp(int(pieces[4]))
            f.write('Set-Cookie3: %s=%s; path=%s; domain=%s; expires="%s"; version=0\n' % (pieces[5], pieces[6], pieces[2], pieces[0], d.isoformat() + 'Z' ))

```

**Comment by sairuk** [comment]
this is a cleaner solution, same deal tho.

```
#!/usr/bin/env python3

from http.cookiejar import LWPCookieJar
from http.cookiejar import MozillaCookieJar

cookies = 'gog-cookies.dat'
mcookies = 'cookies-gog-com.txt'

mjar = MozillaCookieJar(mcookies)
jar = LWPCookieJar()

mjar.load()
for entry in mjar:
    jar.set_cookie(entry)

jar.save(cookies, ignore_discard=True)
```

**Comment by sairuk** [comment]
the code to convert the ff exported cookies is already in `gogrepo.py` at ln:246 as I thought and it takes roughly the same approach as my second script above. but fails for me during the run when accessed from within the script, odd.

```
    # try to import as mozilla 'cookies.txt' format
    try:
        tmp_jar = cookiejar.MozillaCookieJar(global_cookies.filename)
        tmp_jar.load()
        for c in tmp_jar:
            global_cookies.set_cookie(c)
        global_cookies.save()
        return
    except IOError:
        pass
```

**Comment by sairuk** [comment]
```
cookiejar.MozillaCookieJar.magic_re = r'.*'  # bypass the hardcoded "Netscape HTTP Cookie File" check
```

this is what was causing the conversion to fail under python3.9

**Comment by sairuk** [comment]
there is a new version available that should fix the conversion issues. The exported cookie file can be called either `gog-cookies.dat` or `cookies-gog-com.txt` it should find and convert either

https://github.com/sairuk/gogrepo

**Comment by Mythris29** [comment]
Updated it and it's working! I really appreciate your time and effort on this.

**Comment by sairuk** [comment]
great thanks for letting me know, i'll have a look into the login process at some point in time. my expectation was always to cut back across to the main project once the last round of problems were dealt with however my fork is diverging more and more with fixes, i'll still do a pull request at some point on the main project.

**Comment by OGDemoss** [comment]
Working for me also, thanks sairuk!

**Comment by sairuk** [comment]
retronas testing gogrepo integration now has the ability to
- filter on language as per this request https://github.com/sairuk/gogrepo/pull/8#issuecomment-2264136905 (the trade off for the time being is you cannot download all languages anymore from the menu)
- import a cookies file from `<retronas path>/config/gog-cookies.dat`  which should be accessible over the standard retronas samba share, i'd expect importing cookies will always be more reliable than the login flow in the script

**Comment by sairuk** [comment]
retronas has done what it can to workaround this issue, reset is up to the script so closing this now
