### ISSUE TITLE
Samba Installation Just Hangs

### ISSUE THREAD

**Issue by SamuelBanya** [retronas/retronas#409]
### Details

Hey there,
I am in the 'Install' section of 'retronas' menu, and I noticed it just hangs there for a few minutes. It has all the asterisks loaded for 'Install from repos', and does nothing.

Is that normal to take that long? Or did it hang up for whatever reason?

**Comment by sairuk** [comment]
on my test vm it takes 8s to install samba, on an rpi4 under load it takes longer at 37s but still does not hang, although the initial gathering of facts to determine what packages are required for the distro is slow on the rpi4

so you have an issue on your end, your device may be underspecced or you are not letting it run to completion

it is expected that general help is requested as a discussion, as per the prompts when you raise an issue

https://github.com/orgs/retronas/discussions

**Comment by sairuk** [comment]
if it hangs i doubt the underlying vm is actually working properly, confirm your internet works etc, this doesn't seem like an issue with retronas.

i have an rpi4 4GB

grab the console error output so we can see what you are seeing, 

also output of (as your retronas user)
- `whoami`
- `cat /os-release`
- `uname -a`
- `sudo -l`
- `sudo apt-get update`
- `ansible-playbook --version`
- `curl -IL 'https://github.com'`
- `cat /opt/retronas/ansible/retronas_vars.yml`

and assuming you haven't changed the base retronas directory
- `cat /data/retronas/config/retronas_packages.ini`

**Comment by sairuk** [comment]
closing this no response in 2wks
