### ISSUE TITLE
Just An Idea: Distributable RetroNAS VM?

### ISSUE THREAD

**Issue by SamuelBanya** [retronas/retronas#410]
### Details

Hey there,
I was thinking, is it possible for you guys to share a working Debian 11 VM for Virtualbox so that new users like me can play around with it?

Asking since I am having issues with my current install, and would want to look at what was done by one of your teammates to compare. Thanks

**Comment by sairuk** [comment]
we have a discussions area for suggestions and feature requests

https://github.com/orgs/retronas/discussions
