### ISSUE TITLE
syncthing and symlink not working together?

### ISSUE THREAD

**Issue by JayBee-git** [retronas/retronas#412]
### Details

I am not 100% sure it's a bug or a lack of feature, but I setup my Pi with retronas, everything works nice, but it seems syncthing just doesn't want to see/sync any of the symlink folders, only real files/folders, preventing me from using it with any of the OS dependent folders like emudeck, mister or batocera).
Is there a way to fix that issue? I have been looking online a lot but I cannot find a single information on the subject with retronas.

**Comment by sairuk** [comment]
this would be better as a discussion until it were established there is an actual issue to fix with the retronas implementation, however reading the doco for the tool, which we are not responsible for mentions symbolic links will not be followed.

as per the syncthing faq: "Symbolic links (synced, except on Windows, but never followed)" so it'll sync as a link
