### ISSUE TITLE
changing options appears to do nothing

### ISSUE THREAD

**Issue by Jimbo7136** [retronas/retronas#418]
### Details

After installing retronas, attempted to change global configuration options ie username, password, directory, etc.

None of the changes appeared to make any difference after oking. All options remained unchanged.

Currently unable to login to samba share due to inability to change password and no known default password.

**Comment by sairuk** [comment]
switch to the testing branch and advise if there are still issues. i've tested `main` on my testing vm and there is only a known cosmetic issue under normal operation all updates are made to the appropriate places.

there is a ui bug that doesn't show the username/group updates as per https://github.com/retronas/retronas/issues/406 the changes are still applied you can verify by reviewing `/opt/retronas/ansible/retronas_vars.yml`

there is no default password, as mentioned [here](https://github.com/retronas/retronas/issues/407) make sure to change the password using the listed procedure.

**Comment by sairuk** [comment]
passwords aren't stored in the retronas_vars file, they are stored in the required locations for the tools depending on what is installed.

You can switch branches either by following [this page](https://github.com/retronas/retronas/wiki/Testing-RetroNAS) or by using the menu item in `Update -> Branch`

**Comment by Jimbo7136** [comment]
It was my mistake. I got it figured out. Thank you.
