### ISSUE TITLE
Error during cockpit install causing RetroNAS to stop working properly

### ISSUE THREAD

**Issue by zenaro147** [retronas/retronas#419]
### Details

Hi guys!

After trying to install cockpit on my retronas server (behind a Jail on my Truenas server) the entire thing stops to work (including my samba shares) :(

the Cockpit installation finish with this error
`TASK [cockpit-packages - install prerequisite packages] **********************************************************************************************************************************************************************************************************************************************************************
Friday 18 October 2024  11:39:30 -0300 (0:00:00.018)       0:09:31.642 ******** 
fatal: [localhost]: FAILED! => {"cache_update_time": 1729262111, "cache_updated": false, "changed": false, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"       install 'lm-sensors=1:3.6.0-7.1'' failed: E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/libsensors-config_3.6.0-7.1_all.deb  Temporary failure resolving 'deb.debian.org'\nE: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/libsensors5_3.6.0-7.1_amd64.deb  Temporary failure resolving 'deb.debian.org'\nE: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/lm-sensors_3.6.0-7.1_amd64.deb  Temporary failure resolving 'deb.debian.org'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "rc": 100, "stderr": "E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/libsensors-config_3.6.0-7.1_all.deb  Temporary failure resolving 'deb.debian.org'\nE: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/libsensors5_3.6.0-7.1_amd64.deb  Temporary failure resolving 'deb.debian.org'\nE: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/lm-sensors_3.6.0-7.1_amd64.deb  Temporary failure resolving 'deb.debian.org'\nE: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?\n", "stderr_lines": ["E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/libsensors-config_3.6.0-7.1_all.deb  Temporary failure resolving 'deb.debian.org'", "E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/libsensors5_3.6.0-7.1_amd64.deb  Temporary failure resolving 'deb.debian.org'", "E: Failed to fetch http://deb.debian.org/debian/pool/main/l/lm-sensors/lm-sensors_3.6.0-7.1_amd64.deb  Temporary failure resolving 'deb.debian.org'", "E: Unable to fetch some archives, maybe run apt-get update or try with --fix-missing?"], "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following package was automatically installed and is no longer required:\n  nginx-common\nUse 'sudo apt autoremove' to remove it.\nThe following additional packages will be installed:\n  libsensors-config libsensors5\nSuggested packages:\n  fancontrol read-edid i2c-tools\nThe following NEW packages will be installed:\n  libsensors-config libsensors5 lm-sensors\n0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.\nNeed to get 146 kB of archives.\nAfter this operation, 518 kB of additional disk space will be used.\nIgn:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1\nIgn:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1\nIgn:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1\nIgn:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1\nIgn:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1\nIgn:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1\nIgn:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1\nIgn:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1\nIgn:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1\nErr:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1\n  Temporary failure resolving 'deb.debian.org'\nErr:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1\n  Temporary failure resolving 'deb.debian.org'\nErr:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1\n  Temporary failure resolving 'deb.debian.org'\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following package was automatically installed and is no longer required:", "  nginx-common", "Use 'sudo apt autoremove' to remove it.", "The following additional packages will be installed:", "  libsensors-config libsensors5", "Suggested packages:", "  fancontrol read-edid i2c-tools", "The following NEW packages will be installed:", "  libsensors-config libsensors5 lm-sensors", "0 upgraded, 3 newly installed, 0 to remove and 0 not upgraded.", "Need to get 146 kB of archives.", "After this operation, 518 kB of additional disk space will be used.", "Ign:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1", "Ign:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1", "Ign:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1", "Ign:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1", "Ign:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1", "Ign:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1", "Ign:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1", "Ign:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1", "Ign:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1", "Err:1 http://deb.debian.org/debian bookworm/main amd64 libsensors-config all 1:3.6.0-7.1", "  Temporary failure resolving 'deb.debian.org'", "Err:2 http://deb.debian.org/debian bookworm/main amd64 libsensors5 amd64 1:3.6.0-7.1", "  Temporary failure resolving 'deb.debian.org'", "Err:3 http://deb.debian.org/debian bookworm/main amd64 lm-sensors amd64 1:3.6.0-7.1", "  Temporary failure resolving 'deb.debian.org'"]}
`

and now, I can't even run the "retronas" command...
it return this error 
`/opt/retronas/config/retronas.cfg: line 60: MY_IPS: unbound variable`

**Comment by sairuk** [comment]
your networking is broken, both addressing and DNS, what branch are you on and what else changed?

DNS: `Temporary failure resolving 'deb.debian.org'`
Addressing: the `MY_IPS` var is populated on the fly from `ip -4 -br a`

**Comment by zenaro147** [comment]
that's exactly the issue

but idk why this is happens only after install the cockpit :(

after every boot, i need to manually restart the network to get it work again

**Comment by sairuk** [comment]
what `Git Branch` are you on, `main`? It should tell you on the retronas main menu. 

i have no idea how truenas vm networking works, so if its at that level its not an issue with retronas.

other than that check for network startup failure messages
-  `sudo dmesg`
- `sudo systemctl status networking`
- ip a

if you are on `testing` branch because we are testing new features that may be in conflict
- systemctl status NetworkManager

**Comment by zenaro147** [comment]
As far I know, I'm using the main branch.

I will check these messages tomorrow and post here 😀
