### ISSUE TITLE
CurlFTPfs no Packages Error in Debian 12

### ISSUE THREAD

**Issue by phrasius** [retronas/retronas#421]
### Details

CurlFTPfs has been removed from the main bookworm repos and would not install for me using the RetroNAS scripts.  It also failed during the Cockpit Xbox Manager installation.    I understand the Cockpit Xbox Manager is experimental, but this prevents it from installing on Debian.    Thank you for putting this project together.

**Comment by sairuk** [comment]
this is fixed in `testing`, we now compile package

switch branches in the update menu or wait until we're happy testing can be pushed to main.
