### ISSUE TITLE
Passwords do not match

### ISSUE THREAD

**Issue by kosinjak** [retronas/retronas#422]
### Details

#407 #418 [https://github.com/retronas/retronas/wiki/20240909-Changing-your-Password-%E2%80%90-passwords-do-not-match?new_signup=true](url)
When I try to change the password, no menu appears, it just takes me to the error screen
I have taken a video of the issue
[Screencast from 2024-11-03 15-35-07.webm](https://github.com/user-attachments/assets/7ffc62e2-2260-461e-89a2-028e1c47db5b)

**Comment by kosinjak** [comment]
Closing as the issue may be that I am using ubuntu instead of debian.

**Comment by kosinjak** [comment]
Closed as I realised I was using an unsupported OS

**Comment by sairuk** [comment]
https://github.com/orgs/retronas/discussions/123

**Comment by kosinjak** [comment]
I installed Debian 12 in a VM as per the StickFreaks youtube tutorial, and then used SSH to install retronas onto it. The same issue shown in my video happened. Clicking on the "change password" menu will not let me enter a password, it will take me directly to the error screen

**Comment by sairuk** [comment]
interesting i've never been able to replicate any failures here but the video was able to show something to look into

![image](https://github.com/user-attachments/assets/fe548c9b-ed8a-42c8-ac86-f0945f52a022)

**Comment by sairuk** [comment]
What version of dialog is installed?

```
# dialog --version
Version: 1.3-20230209
```

**Comment by sairuk** [comment]
Switch to the testing branch and see if the latest commit fixes it for you.

**Comment by kosinjak** [comment]
> What version of dialog is installed?
> 
> ```
> # dialog --version
> Version: 1.3-20230209
> ```

![Screenshot from 2024-11-07 08-29-30](https://github.com/user-attachments/assets/f136d7e9-4947-427c-b4ac-d0ac07f29b7c)
1.3-2030209

I just tried to do it in the VM instead of SSH and it worked. My video shows Ubuntu and I used SSH on Linux Mint, so it may be a problem with using Retronas on Ubuntu. I'm not sure why the same problem would happen when using SSH through an Ubuntu install when the VM is running Debian...
![Screenshot from 2024-11-07 08-33-10](https://github.com/user-attachments/assets/41b4f963-7ba1-4085-8d3d-2a41c7ae5c05)

**Comment by kosinjak** [comment]
![Screenshot from 2024-11-07 08-36-22](https://github.com/user-attachments/assets/9225e3ae-8a70-433d-ae5f-11f5dd44fba0)
The dialog command shows the same thing on the SSH

**Comment by kosinjak** [comment]
I've taken a video of the problem while running SSH, just in case the error shows up different there.
It seems to be an issue with Ubuntu and Ubuntu-based distros, which I am aware are not supported by Retronas. But it may be worth including a warning that SSH in Ubuntu-based distros can cause problems.
Uploading simplescreenrecorder-2024-11-07_08.46.28.mp4…

**Comment by sairuk** [comment]
ssh/ubuntu doesn't make much sense unless they are purposefully breaking the session somehow

Try the testing branch, see if the latest changes work around the issue. you can switch in the update menu

**Comment by sairuk** [comment]
i've deployed a ubuntu vm and connected over ssh to all my retronas instances without issue. you'll have to try and track down what your ssh session is doing differently causing this to break.

**Comment by kosinjak** [comment]
[test-screen0.webm](https://github.com/user-attachments/assets/f7aa62da-5d1c-4b4c-9ee7-67a07e50f5f3)
I decided to set up my own ubuntu vm, just in case the difference was between running on a vm versus actual hardware, and it still gave me the same error. I am not very technically savvy so I couldn't say what is causing this to happen.

**Comment by sairuk** [comment]
managed to replicate this form a ubuntu desktop session terminal, haven't looked into what/why yet

**Comment by sairuk** [comment]
Problem is the sub-window cannot be created depnding on the terminal size.

Our standard offset resulted in an attempt to create a sub-window passed 80cols at 82cols, if you resize the default Ubuntu terminal (80cols) the password screen renders fine. 

Additionally the error output from the failed sub-window creation was populating the first pass variable which then entered our block for password checking where pass1 (error) didn't match pass2 (empty) and was stuck in a loop because when we tried to redraw the password screen for corrected input it'd crash again.

I have reduced our offset, and captured the failure if it occurs with an error message that suggests resizing the screen may help, then exits the menu.

You can try the fix in the testing branch

**Comment by kosinjak** [comment]
https://github.com/user-attachments/assets/2c98258d-805a-4f0e-8d51-9484add4a65a

The update worked!
