### ISSUE TITLE
Option "-br" is unknown, try "ip -help".

### ISSUE THREAD

**Issue by BILL-BUFALO** [retronas/retronas#424]
### Details

Hello. I am using OrangePy Zero and I try to run **retronas** but I get an error:

> Option "-br" is unknown, try "ip -help".
> Option "-br" is unknown, try "ip -help".
> /opt/retronas/config/retronas.cfg: line 85: MY_IPS: unbound variable

As I understand it, it is related to the version of the ip program.
I tried changing the command in /opt/retronas/config/retronas.cfg and it partly worked, but /opt/retronas/config/retronas.cfg restored the default value. Can you tell me how to bypass this?

**Comment by sairuk** [comment]
You cannot bypass it for normal use, you need to use a supported distro .... what distro are you using?

**Comment by BILL-BUFALO** [comment]
Debian for OrangePy. Yesterday I finally downloaded and installed the latest version of the distribution. And the problem was solved. Thank you.
