### ISSUE TITLE
Nothing is installed on OrangePi Debian

### ISSUE THREAD

**Issue by BILL-BUFALO** [retronas/retronas#425]
### Details

When trying to install any service:

> ERROR! this task 'ansible.builtin.include_vars' has extra params, which is only allowed in the following modules: include, win_shell, import_tasks, add_host, set_fact, command, win_command, shell, script, group_by, import_role, include_role, raw, include_tasks, include_vars, meta
> 
> The error appears to be in '/opt/retronas/ansible/retronas_dependencies.yml': line 23, column 5, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
>   - name: "{{ my_name }} - Load RetroNAS config"
>     ^ here
> We could be wrong, but this one looks like it might be an issue with
> missing quotes. Always quote template expression brackets when they
> start a value. For instance:
> 
>     with_items:
>       - {{ foo }}
> 
> Should be written as:
> 
>     with_items:
>       - "{{ foo }}"
> ERROR! this task 'ansible.builtin.include_vars' has extra params, which is only allowed in the following modules: import_tasks, shell, script, include_tasks, win_command, command, import_role, win_shell, raw, set_fact, group_by, include_vars, include, meta, add_host, include_role
> 
> The error appears to be in '/opt/retronas/ansible/install_samba.yml': line 42, column 5, but may
> be elsewhere in the file depending on the exact syntax problem.
> 
> The offending line appears to be:
> 
> 
>   - name: "{{ my_name }} - Load RetroNAS config"
>     ^ here
> We could be wrong, but this one looks like it might be an issue with
> missing quotes. Always quote template expression brackets when they
> start a value. For instance:
> 
>     with_items:
>       - {{ foo }}
> 
> Should be written as:
> 
>     with_items:
>       - "{{ foo }}"
>

**Comment by sairuk** [comment]
seems like you may still be on an unsupported distro ... check details of `cat /etc/os-release` and `ansible --version`

if you are not on deb12 bookworm (with ansible ~2.14) you are not in a supported software configuration. We don't explicitly support any other sbc hardware than rpi atm, so if you are still trying on an opi0 then its best effort through the supported distro but i'd ask you start a discussion thread to work through any unsupported hw issues not tickets. Noting we wont be adding legacy compatibility as we align with current rpios.

See: https://github.com/retronas/retronas/wiki/Supported-Configurations

Discussions: https://github.com/orgs/retronas/discussions

**Comment by BILL-BUFALO** [comment]
Strange, I installed from the file OrangePi_zero_debian_stretch_server_linux5.3.5_v1.0.tar.gz, but the system says that it is installed:
NAME="Ubuntu"
VERSION="20.04.6 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.6 LTS"

ansible 2.9.6

Anyway, thanks for the explanation.
