### ISSUE TITLE
Unable to install updates for retronas

### ISSUE THREAD

**Issue by rogersta99** [retronas/retronas#427]

**Comment by rogersta99** [comment]
After trying to install updates the following msg is displayed.

E: dpkg was interrupted, you must manually run 'dpkg --configure -a' to correct the problem.

How do you manually run?

**Comment by sairuk** [comment]
standard linux package manager issue not a retronas issue, will generally happen if apt and dpkg are interrupted

open a terminal and run the command as root on your linux install.
